name: skull_king_score_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
